language: python
python:
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev
# install dependencies
install:
  - pip install -r requirements-dev.txt
# run tests via pytest
script:
  - python ./tests/runtests.py