language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev
install:
  - pip install -r requirements-dev.txt
script:
  - flake8 aiorest_ws tests
  - python ./tests/runtests.py